[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
dbirdge_solana = "7iY5TvGUTxfPX2vD71k6xkHCTDKDquruKLtikL9Pmtk7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/0xbigbang/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
